### ISSUE TITLE
How to incorporate population weights?

### ISSUE THREAD

**Issue by calebleedy** [yonghyun-K/GECal#1]
Dear Yonghyun,

Thank you for putting together this package which makes  it easier to recreate the results from your paper. In your paper you mention the difference of knowing the weights for the entire population and estimating the population average weight $\hat \alpha$, but I did not see how to differentiate the two in this package. Thus, I have the following questions:

1. Is the default method `GECalib` implementing the true or estimated population weights? and,
2. How can I run a simulation with the other setup?

Thanks,
Caleb

**Comment by yonghyun-K** [comment]
Dear Caleb,

Thank you very much for your questions! That is a very good point.

1. Is the default method GECalib implementing the true or estimated population weights?
The default method GECalib implements the true population weights.

2. How can I run a simulation with the other setup?
Currently, GECalib does not support the estimation of population weights, which is one of the limitations of the current version. I'm planning to update the code to accommodate unknown population-level design weights, but I would also like to make the functions straightforward and user-friendly. Please feel free to share any comments or suggestions you have regarding this update.

I apologize for the delayed response. I was in military BootCamp until last month, which severely limited my internet access.

Thank you,
Yonghyun

**Comment by calebleedy** [comment]
Yonghyun, thanks for letting me know. This code, especially the code to run your simulation studies was very helpful, and I really appreciate it.
