### ISSUE TITLE
Why the change in the base weights?

### ISSUE THREAD

**Issue by calebleedy** [yonghyun-K/GECal#2]
Hey Yonghyun,

I have another question about this package. I was working through the simulation study in `sim/Sampling.R` and I noticed that the calibration estimators in your sample had starting weights of $1 / n$ when `DS = TRUE`. However, in the example for the `GEcalib` function you have base weights equal to $d_i = 1 / \pi_i$. Why did you make this change?

Thanks,
Caleb

**Comment by yonghyun-K** [comment]
Hi, Caleb! Thank you for your question!

I guess your question is about the following line. (Please correct me if I am wrong)

https://github.com/yonghyun-K/GECal/blob/40ee61e689c173513f1731312317810da683977c/sim/Sampling.R#L491-L495

Your question may arise from my abuse of the object name in the code. The difference between the DS weight can be expressed as follows:

$$
w_i^{\rm DS} = \pi_i^{-1} f(\mathbf z_i' \lambda); \quad w_i^{\rm GEC} = f(\mathbf z_i' \lambda)
$$

In both cases, I used $w_i = d_i f(\mathbf z_i' \lambda)$ with $d_i = \pi_i^{-1}$ for DS weight and $d_i = 1$ for the GEC weights.

I think I should change the object name "d_S" to something else(e.g. q_S) to avoid confusion. 

Please note that the design weights were not uniform for both cases `sim/Sampling.R` and `GEcalib`. Let me know if you have any further questions or comments!

Best regards,
Yonghyun

**Comment by calebleedy** [comment]
Thanks for the explanation. That makes sense to me.
